-- Create profiles table
create table if not exists public.profiles (
  id uuid not null primary key references auth.users (id) on delete cascade,
  username text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create user_settings table
create table if not exists public.user_settings (
  id uuid not null primary key references public.profiles (id) on delete cascade,
  sodium_goal integer default 2300,
  fluid_goal integer default 2000,
  dark_mode boolean default false,
  vital_alerts boolean default true,
  hydration_reminders boolean default true,
  meal_tracking_reminders boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create food_logs table
create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  food_name text not null,
  portion_g numeric,
  energy_kcal numeric,
  sodium_mg numeric,
  image_url text,
  confidence double precision,
  protein_g numeric,
  carbs_g numeric,
  fat_g numeric,
  fiber_g numeric,
  sugar_g numeric,
  potassium_mg numeric,
  magnesium_mg numeric,
  calcium_mg numeric,
  fluid_ml numeric,
  caffeine_mg numeric,
  serving_desc text,
  food_status boolean default true,
  utensil boolean default false
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.food_logs enable row level security;

-- Policies (using do block to avoid error if they exist, or just drop and recreate)
drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

drop policy if exists "Users can view own settings" on public.user_settings;
create policy "Users can view own settings" on public.user_settings
  for select using (auth.uid() = id);

drop policy if exists "Users can update own settings" on public.user_settings;
create policy "Users can update own settings" on public.user_settings
  for update using (auth.uid() = id);

drop policy if exists "Users can view own food logs" on public.food_logs;
create policy "Users can view own food logs" on public.food_logs
  for select using (auth.uid() = profile_id);

drop policy if exists "Users can insert own food logs" on public.food_logs;
create policy "Users can insert own food logs" on public.food_logs
  for insert with check (auth.uid() = profile_id);

drop policy if exists "Users can update own food logs" on public.food_logs;
create policy "Users can update own food logs" on public.food_logs
  for update using (auth.uid() = profile_id);

drop policy if exists "Users can delete own food logs" on public.food_logs;
create policy "Users can delete own food logs" on public.food_logs
  for delete using (auth.uid() = profile_id);

-- Trigger to create profile and settings on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, username)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'username')
  on conflict (id) do nothing;

  insert into public.user_settings (id)
  values (new.id)
  on conflict (id) do nothing;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
